GENRE_REGEX: dict[str, list[str]] = {
    # --- Rock & Verwandte ---
    "rock": [
        r"\brock\b",
        r"\bclassic\s+rock\b",
        r"\bsoft\s+rock\b",
        r"\bblues[-\s]?rock\b",
        r"\brock\s+pop\b",
        r"\bpop\s+rock\b",
        r"\brock/pop\b",
        r"\brock\s*&\s*roll\b",
        r"\brock\s+and\s+roll\b",
        r"\brock[-\s]?and[-\s]?indie\b",
        r"\balbum\s+rock\b",
        r"\bamerican\s+trad\s+rock\b",
        r"\bheartland\s+rock\b",
        r"\bspace\s+rock\b",
        r"\bspace\s+rock\s+revival\b",
        r"\bacoustic\s+rock\b",
        r"\bjazz[-\s]?rock\b",
        r"\bprog(ressive)?\s+rock\b",
    ],
    "alternative_rock": [
        r"\balternative\s+rock\b",
        r"\balt[-\s]?rock\b",
        r"\balt\s+rock\b",
        r"\balternrock\b",
        r"\bpost[-\s]?grunge\b",
        r"\bpost\s+grunge\b",
        r"\bpost[-\s]?grunge\s+alternative\s+rock\b",
        r"\bgeneral\s+alternative\s+rock\b",
        r"\bamerican\s+trad\s+rock\b",  # kannst du ggf. zu "rock" schieben
    ],
    "indie_rock": [
        r"\bindie\s+rock\b",
        r"\balt\s+rock\b",
        r"\balternative/indie\s+rock\b",
        r"\bindie\b",          # vorsichtig: sehr breit – zur Not rausnehmen
        r"\brock\s+and\s+indie\b",
        r"\bindietronica\b",
        r"\bgarage\s+rock\s+revival\b",
        r"\bpost[-\s]?britpop\b",
        r"\bpost[-\s]?punk\s+revival\b",
    ],
    "punk": [
        r"\bpunk\b",
        r"\bpunk\s+rock\b",
        r"\bpunk[-\s]?pop\b",
        r"\bpunk\s+pop\b",
        r"\bpunk[-\s]?metal\b",
        r"\bskate\s*punk\b",
        r"\bskatepunk\b",
        r"\bgarage\s+punk\b",
        r"\banarcho[-\s]?punk\b",
        r"\bgypsy\s+punk\b",
        r"\bpunk\s+blues\b",
        r"\bpunk\s+revival\b",
        r"\bpunk/new\s*wave\b",
        r"\bnew\s+wave/post[-\s]?punk\s+revival\b",
        r"\bpost[-\s]?punk\b",
    ],
    "metal": [
        r"\bmetal\b",
        r"\bheavy\s+metal\b",
        r"\balternative\s+metal\b",
        r"\balt[-\s]?metal\b",
        r"\bblack\s+metal\b",
        r"\bdeath\s+metal\b",
        r"\bdoom\s+metal\b",
        r"\bthrash\s+metal\b",
        r"\bspeed\s+metal\b",
        r"\bspeed/thrash\s+metal\b",
        r"\bpower\s+metal\b",
        r"\bprogressive\s+metal\b",
        r"\bindustrial\s+metal\b",
        r"\bgoth(ic)?\s+metal\b",
        r"\bsymphonic\s+metal\b",
        r"\bsymphonic\s+black\s+metal\b",
        r"\bfolk\s+metal\b",
        r"\bstoner\s+metal\b",
        r"\bmelodic\s+metalcore\b",
        r"\bmetalcore\b",
        r"\bmelodic\s+death\s+metal\b",
        r"\bgroove\s+metal\b",
        r"\brap[-\s]?metal\b",
        r"\brapmetal\b",
        r"\brap\s*metal\b",
        r"\bchristian\s+metal\b",
        r"\bneo[-\s]?classical\s+metal\b",
    ],

    # --- Pop & Verwandte ---
    "pop": [
        r"\bpop\b",
        r"\bpop\s+rock\b",
        r"\bpop/rock\b",
        r"\bclassic\s+pop\s+and\s+rock\b",
        r"\bcontemporary\s+pop/rock\b",
        r"\bteen\s+pop\b",
        r"\bdance[-\s]?pop\b",
        r"\bpop\s+and\s+chart\b",
        r"\bpop\s+metal\b",
        r"\bpop[-\s]?metal\b",
        r"\bpop\s+folk\b",
        r"\bpop[-\s]?folk\b",
        r"\bpop\s+rap\b",
        r"\bpop\s+soul\b",
        r"\bother\s+pop\b",
        r"\bgeneral\s+pop\b",
        r"\bgeneral\s+pop\s+vocal\b",
    ],
    "synth_pop": [
        r"\bsynth[-\s]?pop\b",
        r"\belectro\s*pop\b",
        r"\belectropop\b",
        r"\bsynth\s+funk\b",
        r"\bnew\s+wave\b",  # optional; könnte auch eigenes Genre sein
    ],
    "art_pop": [
        r"\bart\s+pop\b",
        r"\bavant[-\s]?garde\s+pop\b",
        r"\bchamber\s+pop\b",
        r"\bbaroque\s+pop\b",
        r"\bchamber\s+folk\b",  # je nach Geschmack eher "folk"
    ],

    # --- Electronic / Dance ---
    "electronic": [
        r"\belectronic\b",
        r"\belectronica\b",
        r"\bdance\s+and\s+electronica\b",
        r"\belectronica\s+dance\b",
        r"\belectronic\s+rock\b",
        r"\bclub/dance\b",
        r"\bnon-music\b",  # könnte man rausnehmen; eher Metadatum
    ],
    "house": [
        r"\bhouse\b",
        r"\bdeep\s+house\b",
        r"\btech\s*house\b",
        r"\bclub[-\s]?house\b",
        r"\beuro\s+house\b",
        r"\bfrench\s+house\b",
        r"\bfunky\s+house\b",
        r"\bleft[-\s]?field\s+house\b",
    ],
    "techno": [
        r"\btechno\b",
        r"\bacid\s+house\b",
        r"\bacid\s+jazz\b",  # eher jazz/funk – optional
    ],
    "trance": [
        r"\btrance\b",
    ],
    "ambient": [
        r"\bambient\b",
        r"\bambient\s+pop\b",
        r"\bdark\s+ambient\b",
        r"\bdrone\b",
    ],
    "idm": [
        r"\bidm\b",
        r"\belectroclash\b",
        r"\bfuturepop\b",
        r"\bglitch\b",
        r"\bglitch\s+pop\b",
    ],
    "drum_and_bass": [
        r"\bdrum\s+and\s+bass\b",
        r"\bbreakbeat\b",
        r"\bbig\s+beat\b",
        r"\bbreaks\b",
    ],
    "trip_hop": [
        r"\btrip[-\s]?hop\b",
        r"\bdowntempo\b",
        r"\blounge\b",
    ],

    # --- Hip-Hop / R&B ---
    "hip_hop": [
        r"\bhip[-\s]?hop\b",
        r"\bhiphop\b",
        r"\bhip\s+hop\s+rap\b",
        r"\bhip\s+hop\s+rnb\s+and\s+dance\s+hall\b",
        r"\bconscious\s+hip\s*hop\b",
        r"\bexperimental\s+hip\s*hop\b",
        r"\bgangsta\s+rap\b",
        r"\beast\s+coast\s+rap\b",
        r"\beast\s+coast\s+hip\s*hop\b",
        r"\bwest\s+coast\s+rap\b",
        r"\bunderground\s+rap\b",
        r"\brap\b",
        r"\brap[-\s]?rock\b",
        r"\brap\s*rock\b",
        r"\brapcore\b",
        r"\bhip\s+hop\s+rap\b",
        r"\balternative\s+rap\b",
        r"\balternative\s+hip\s*hop\b",
    ],
    "rnb_soul": [
        r"\br[&\s]?b\b",
        r"\br\s*n\s*b\b",
        r"\brnb/swing\b",
        r"\brnb\s+sw(ing)?\b",
        r"\bsoul\b",
        r"\bblue-eyed\s+soul\b",
        r"\bcontemporary\s+r&b\b",
        r"\bfunk\s+soul\b",
    ],
    "funk": [
        r"\bfunk\b",
        r"\bfunk\s+metal\b",
        r"\bfunk\s+rock\b",
        r"\bfunky\s+house\b",
    ],

    # --- Folk / Country ---
    "folk": [
        r"\bfolk\b",
        r"\bfolk\s+rock\b",
        r"\bfolk[-\s]?rock\b",
        r"\bfolk\s+punk\b",
        r"\bfolk\s+pop\b",
        r"\bcontemporary\s+folk\b",
        r"\banti[-\s]?folk\b",
        r"\bchamber\s+folk\b",
        r"\bneofolk\b",
        r"\bprogressive\s+folk\b",
    ],
    "country": [
        r"\bcountry\b",
        r"\bcountry\s+rock\b",
        r"\bcountry[-\s]?rock\b",
        r"\bcontemporary\s+country\b",
        r"\bcountry\s+blues\b",
        r"\balt[-\s]?country\b",
        r"\balternative\s+country\b",
        r"\balternative\s+country[-\s]?rock\b",
    ],
    "americana": [
        r"\bamericana\b",
    ],

    # --- Singer-Songwriter / Acoustic ---
    "singer_songwriter": [
        r"\bsinger[-\s]?songwriter\b",
        r"\bsinger/songwriter\b",
        r"\balternative\s+singer/songwriter\b",
        r"\bcontemporary\s+singer/songwriter\b",
    ],
    "acoustic": [
        r"\bacoustic\b",
        r"\bacoustic\s+rock\b",
        r"\bemo[-\s]?folk\b",
    ],

    # --- Emo / Hardcore / Post-XXX ---
    "emo": [
        r"\bemo\b",
        r"\bemo\s+pop\b",
        r"\bemo[-\s]?folk\b",
        r"\bscreamo\b",
    ],
    "hardcore": [
        r"\bhardcore\b",
        r"\bhardcore\s+punk\b",
        r"\bhardcore\s+hip\s*hop\b",
        r"\bmelodic\s+hardcore\b",
        r"\bmathcore\b",
        r"\bpost[-\s]?hardcore\b",
    ],
    "post_rock": [
        r"\bpost[-\s]?rock\b",
        r"\bpost\s+rock\b",
        r"\bpost[-\s]?metal\b",
        r"\bpost[-\s]?industrial\b",
    ],

    # --- Shoegaze / Dreampop / Neo-psychedelia ---
    "shoegaze": [
        r"\bshoegaze\b",
        r"\bshoegazer\b",
        r"\bdream\s+pop\b",
        r"\bneo[-\s]?psychedelia\b",
        r"\bpsychedelic\s+rock\b",
        r"\bpsychedelic\s+pop\b",
        r"\bpsychedelic\b",
    ],

    # --- Jazz / Classical / World ---
    "jazz": [
        r"\bjazz\b",
        r"\bjazz[-\s]?rock\b",
        r"\bjazz\s+rock\b",
        r"\bjazz\s+rap\b",
        r"\bacid\s+jazz\b",
        r"\bcontemporary\s+jazz\b",
        r"\bvocal\s+jazz\b",
        r"\bsmooth\s+jazz\b",
        r"\bbig\s+band\b",
    ],
    "classical": [
        r"\bclassical\b",
        r"\bmodern\s+classical\b",
        r"\bneo[-\s]?classical\b",
        r"\bclassical\s+crossover\b",
        r"\borchestral\b",
    ],
    "world": [
        r"\bworld\b",
        r"\bchanson\b",
        r"\bchanson\s+fran[çc]aise\b",
        r"\breggae\b",
        r"\breggae[-\s]?pop\b",
        r"\bragga\s*hiphop\b",
        r"\blatin\b",
        r"\blatin\s+pop\b",
        r"\bbossa\s+nova\b",
        r"\bbluegrass\b",
        r"\bhumppa\b",
    ],
}