"""Compatibility re-exports for Streamlit pages (thin facade over split modules)."""

from __future__ import annotations

from pages import profile_session as _profile_session
from pages._streamlit_ctx import st
from pages.filter_state import (
    DEFAULT_PLATTENTESTS_RATING_FILTER_MAX,
    DEFAULT_PLATTENTESTS_RATING_FILTER_MIN,
    FILTER_ACCOUNT_SAVE_PROMPT_ACTIVE_KEY,
    FILTER_FLOW_WIDGET_KEY_OVERALL_ALPHA,
    FILTER_FLOW_WIDGET_KEY_OVERALL_BETA,
    FILTER_FLOW_WIDGET_KEY_OVERALL_GAMMA,
    FILTER_FLOW_WIDGET_KEY_RATING_RANGE,
    FILTER_FLOW_WIDGET_KEY_STYLE_MATCH_PCT,
    FILTER_FLOW_WIDGET_KEY_YEAR_RANGE,
    FILTER_FLOW_WIDGET_KEYS,
    FILTER_PLATTENLABEL_MULTISELECT_KEY,
    PLATTENLABEL_SONSTIGE_UI,
    TASTE_WIZARD_WIDGET_KEY_PREFIXES,
    WIZARD_ACCOUNT_SAVE_INTENT_KEY,
    clamp_plattentests_rating_filter_range,
    clamp_year_filter_bounds,
    collapse_plattenlabel_ui_selection,
    expand_plattenlabel_ui_selection,
    get_selected_communities,
    normalize_filter_expander_vspace_gap,
    plattenlabel_filter_passes,
)
from pages.page_css import (
    OVERALL_WEIGHT_TRADEOFF_RED_DARK,
    OVERALL_WEIGHT_TRADEOFF_RED_LIGHT,
    OVERALL_WEIGHT_TRADEOFF_RED_MID,
    inject_recommendation_flow_shell_css,
    recommendation_flow_shell_css_rules,
)
from pages.page_formatting import (
    STYLE_MATCH_FILTER_PERCENT_STEP,
    build_community_broad_category_index,
    community_display_label,
    format_record_labels_for_card,
    format_release_date,
    format_style_match_range_display,
    format_style_weight_example_artists,
    overall_weights_display_percents,
    overall_weights_tradeoff_bar_html,
    recommendation_card_community_tags_html,
    recommendation_card_meta_parts,
    release_year_for_card_meta,
    style_match_percent_tuple_for_slider,
    style_match_scores_from_percent_slider,
)
from pages.profile_session import (
    SESSION_TOKEN_COOKIE_NAME,
    bootstrap_profile_session,
    build_session_profile_payload,
    clear_active_profile_slug_cookie,
    clear_session_token_cookie,
    logout_active_profile,
    peek_active_profile_slug_from_context_cookies,
    peek_session_token_from_context_cookies,
    persist_active_profile_from_session,
    persist_active_profile_slug_cookie,
    persist_session_token_cookie,
    profile_cookie_manager,
    render_profile_sidebar,
    render_toolbar,
    restore_active_profile_from_cookie_if_needed,
    save_current_profile_to_disk,
)
from pages.wizard_state import (
    has_step1_state,
    has_step2_state,
    has_step3_state,
    prune_communities_to_selected_broad_categories,
    prune_weights_to_selected_communities,
    refresh_taste_wizard_after_filter_save,
    reset_step1_cascade,
    reset_step2_cascade,
    reset_step3,
    reset_taste_preferences,
    session_taste_setup_complete,
)

from music_review.dashboard.data_cache import (
    cached_load_broad_categories_res_10,
    cached_max_release_year_from_corpus,
    cached_min_release_year_from_corpus,
)
from music_review.dashboard.streamlit_branding import (
    ensure_plattenradar_dashboard_chrome,
)
from music_review.dashboard.user_db import get_connection as get_db_connection
from music_review.dashboard.user_profile_store import ACTIVE_PROFILE_SESSION_KEY

# Test hooks: patchable aliases for private profile_session helpers.
_invalidate_current_session_token = _profile_session._invalidate_current_session_token
_read_session_token_from_cookies = _profile_session._read_session_token_from_cookies
_safe_cookie_manager_delete = _profile_session._safe_cookie_manager_delete

__all__ = [
    "ACTIVE_PROFILE_SESSION_KEY",
    "DEFAULT_PLATTENTESTS_RATING_FILTER_MAX",
    "DEFAULT_PLATTENTESTS_RATING_FILTER_MIN",
    "FILTER_ACCOUNT_SAVE_PROMPT_ACTIVE_KEY",
    "FILTER_FLOW_WIDGET_KEYS",
    "FILTER_FLOW_WIDGET_KEY_OVERALL_ALPHA",
    "FILTER_FLOW_WIDGET_KEY_OVERALL_BETA",
    "FILTER_FLOW_WIDGET_KEY_OVERALL_GAMMA",
    "FILTER_FLOW_WIDGET_KEY_RATING_RANGE",
    "FILTER_FLOW_WIDGET_KEY_STYLE_MATCH_PCT",
    "FILTER_FLOW_WIDGET_KEY_YEAR_RANGE",
    "FILTER_PLATTENLABEL_MULTISELECT_KEY",
    "OVERALL_WEIGHT_TRADEOFF_RED_DARK",
    "OVERALL_WEIGHT_TRADEOFF_RED_LIGHT",
    "OVERALL_WEIGHT_TRADEOFF_RED_MID",
    "PLATTENLABEL_SONSTIGE_UI",
    "SESSION_TOKEN_COOKIE_NAME",
    "STYLE_MATCH_FILTER_PERCENT_STEP",
    "TASTE_WIZARD_WIDGET_KEY_PREFIXES",
    "WIZARD_ACCOUNT_SAVE_INTENT_KEY",
    "bootstrap_profile_session",
    "build_community_broad_category_index",
    "build_session_profile_payload",
    "cached_load_broad_categories_res_10",
    "cached_max_release_year_from_corpus",
    "cached_min_release_year_from_corpus",
    "clamp_plattentests_rating_filter_range",
    "clamp_year_filter_bounds",
    "clear_active_profile_slug_cookie",
    "clear_session_token_cookie",
    "collapse_plattenlabel_ui_selection",
    "community_display_label",
    "ensure_plattenradar_dashboard_chrome",
    "expand_plattenlabel_ui_selection",
    "format_record_labels_for_card",
    "format_release_date",
    "format_style_match_range_display",
    "format_style_weight_example_artists",
    "get_db_connection",
    "get_selected_communities",
    "has_step1_state",
    "has_step2_state",
    "has_step3_state",
    "inject_recommendation_flow_shell_css",
    "logout_active_profile",
    "normalize_filter_expander_vspace_gap",
    "overall_weights_display_percents",
    "overall_weights_tradeoff_bar_html",
    "peek_active_profile_slug_from_context_cookies",
    "peek_session_token_from_context_cookies",
    "persist_active_profile_from_session",
    "persist_active_profile_slug_cookie",
    "persist_session_token_cookie",
    "plattenlabel_filter_passes",
    "profile_cookie_manager",
    "prune_communities_to_selected_broad_categories",
    "prune_weights_to_selected_communities",
    "recommendation_card_community_tags_html",
    "recommendation_card_meta_parts",
    "recommendation_flow_shell_css_rules",
    "refresh_taste_wizard_after_filter_save",
    "release_year_for_card_meta",
    "render_profile_sidebar",
    "render_toolbar",
    "reset_step1_cascade",
    "reset_step2_cascade",
    "reset_step3",
    "reset_taste_preferences",
    "restore_active_profile_from_cookie_if_needed",
    "save_current_profile_to_disk",
    "session_taste_setup_complete",
    "st",
    "style_match_percent_tuple_for_slider",
    "style_match_scores_from_percent_slider",
]
